FROM node:latest as build
WORKDIR /usr/local/app
COPY . .
RUN npm install -g npm@10.2.2
RUN npm install
CMD ["npm", "run" , "build", "--prod"]
FROM nginx:latest
COPY --from=build /usr/local/app/build /usr/share/nginx/html
EXPOSE 80