services: 
  backend:
    restart: on-failure
    container_name: backend
    image: carlosmz87/semi1-proyecto2-backend:local-V1
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - app_net
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      AWS_USER_POOL_ID: ${AWS_USER_POOL_ID}
      AWS_CLIENT_ID: ${AWS_CLIENT_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_BUCKET_FOLDER_PROFILE: ${AWS_BUCKET_FOLDER_PROFILE}
      AWS_BUCKET_FOLDER_PUBLIC: ${AWS_BUCKET_FOLDER_PUBLIC}

  frontend:
    depends_on:
      - backend
    container_name: frontend
    image: carlosmz87/semi1-proyecto2-frontend:local-V1
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app_net
    links:
      - backend
    environment:
      REACT_APP_REQUEST_URL: ${REACT_APP_REQUEST_URL}
      REACT_APP_REQUEST_S3_URL: ${REACT_APP_REQUEST_S3_URL}
      REACT_APP_REQUEST_TRANSLATE: ${REACT_APP_REQUEST_TRANSLATE}
        
networks:
  app_net:
    driver: bridge