services:
  social_semi_db:
    container_name: social_semi_db
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
    ports:
      - "3306:3306"
    volumes:
      - mysql-semi-vol:/var/lib/mysql
      - ./social-semi_init.sql:/docker-entrypoint-initdb.d/social-semi_init.sql
    networks:
      - app_net

volumes:
  mysql-semi-vol:

networks:
  app_net:
    driver: bridge
